app-builder:
  build:
    image: 478489794941.dkr.ecr.us-east-1.amazonaws.com/default:${CI_BUILD_ID}
    context: .
    dockerfile: Dockerfile.build
  cached: true
aws_generator: 
  image: codeship/aws-ecr-dockercfg-generator
  encrypted_env_file: env-ecs.encrypted
  add_docker: true
awsdeployment:
  image: codeship/aws-deployment
  encrypted_env_file: env-ecs.encrypted
  environment:
    - AWS_DEFAULT_REGION=us-east-1
