app-builder-stage:
  build:
    image: weave/stage
    context: .
    dockerfile: Dockerfile.build
  cached: true
app-builder-front:
  build:
    image: 478489794941.dkr.ecr.us-east-1.amazonaws.com/front
    context: .
    dockerfile: Dockerfile-front.build
  cached: true
aws_generator: 
  image: codeship/aws-ecr-dockercfg-generator
  encrypted_env_file: env-ecs.encrypted
  add_docker: true

