app-build:
  build:
    image: build-sbt
    context: .
    dockerfile: Dockerfile.build
  cached: true
app-build-run:
  build:
    image: build-sbt-run
    context: .
    dockerfile: Dockerfile.build-run
  cached: false
  